### ISSUE TITLE
错误: 找不到或无法加载主类

### ISSUE THREAD

**Issue by inuex** [apache/seatunnel#7364] opened 2024-08-10 02:49 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用 apache-seatunnel-2.3.6，执行以下的语句
.\bin\seatunnel.cmd --config .\config\v2.batch.config.template -m local

会报类似这样的错误， 请问是什么原因？
错误: 找不到或无法加载主类 9422194221.90

### SeaTunnel Version

2.3.6

### SeaTunnel Config

```conf
v2.batch.config.template
```

### Running Command

```shell
.\bin\seatunnel.cmd --config .\config\v2.batch.config.template -m local
```

### Error Exception

```log
错误: 找不到或无法加载主类 9422194221.90
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment] 2024-08-11 02:10
Compiled by yourself? And the system is window

**Comment by inuex** [comment] 2024-08-11 03:21
> Compiled by yourself? And the system is window

It is a Windows 11 system. After extracting version 2.3.6 and testing it in the home directory, sometimes this error may be reported

**Comment by BigTailMonkey** [comment] 2024-08-12 01:39
I also encountered the same issue, but after a few more attempts, it worked normally.
我也遇到过同样的问题，重试了几次运行就能跑了。

**Comment by Carl-Zhou-CN** [comment] 2024-08-13 03:52
> > Compiled by yourself? And the system is window
> 
> It is a Windows 11 system. After extracting version 2.3.6 and testing it in the home directory, sometimes this error may be reported

Most of the probability is caused by newlines, you can check

**Comment by inuex** [comment] 2024-08-15 03:36
> > > Compiled by yourself? And the system is window
> > 
> > 
> > It is a Windows 11 system. After extracting version 2.3.6 and testing it in the home directory, sometimes this error may be reported
> 
> Most of the probability is caused by newlines, you can check

Thinks

**Comment by Carl-Zhou-CN** [comment] 2024-08-16 05:47
It looks like it has been resolved and I will close this issue

**Closed as completed by Carl-Zhou-CN** 2024-08-16 05:47 UTC
Labels: bug
