### ISSUE TITLE
[Bug] [File Connector V2] Data file name will duplicate when use SeaTunnel Engine

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#3611] opened 2022-11-30 08:35 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/32193458/204746972-19f141d4-a8c6-4996-acc8-a40819a0c6d7.png">

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/32193458/204746993-426587ef-d563-4c49-b7c8-ead21e854abc.png">

### SeaTunnel Version

ALL 

### SeaTunnel Config

```conf
CI: https://github.com/apache/incubator-seatunnel/pull/3456#pullrequestreview-1198820624
```

### Running Command

```shell
CI: https://github.com/apache/incubator-seatunnel/pull/3456#pullrequestreview-1198820624
```

### Error Exception

```log
CI: https://github.com/apache/incubator-seatunnel/pull/3456#pullrequestreview-1198820624
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TaoZex** [comment] 2022-11-30 09:00
I want to try this issue.Please assign to me.

**Comment by TaoZex** [comment] 2022-12-01 08:08
This is probably not a bug and the file name is renamed to right form during the 2PC commit phase.

**Comment by TaoZex** [comment] 2022-12-09 03:16
JobId was initialized before dag was resolved, but PipelineId was created for executeplan after dag was resolved. Therefore,
JobId and Pipelineid were created at different locations. I have communicated with @Hisoka-X ,this does not seem to be able to pass jobId+pipelneId directly to the connector.

**Comment by EricJoy2048** [comment] 2022-12-09 03:32
> JobId was initialized before dag was resolved, but PipelineId was created for executeplan after dag was resolved. Therefore, JobId and Pipelineid were created at different locations. I have communicated with @Hisoka-X ,this does not seem to be able to pass jobId+pipelneId directly to the connector.

Yes, you are right. We plan fix it in `file sink connector`. @Hisoka-X  will finish this work.

Thanks.

**Comment by TaoZex** [comment] 2022-12-09 03:46
OK. Thanks for your reply.

**Closed as completed** 2022-12-15 03:10 UTC
Labels: bug, help wanted
