### ISSUE TITLE
[Bug] [deploy] Version 2.1.1.  No configuration setting found for key 'env'. 

### ISSUE THREAD

**Issue by zjw-zjw** [apache/seatunnel#1846] opened 2022-05-11 03:51 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Version 2.1.1, when using spark on yarn mode to start,[报org.apache.seatunnel.shade.com](http://xn--org-pb6f.apache.seatunnel.shade.com/) .typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'. Have you ever encountered

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
env {
    spark.app.name = "seatunnel_mongo_to_ck_core_device_demo"
    # You can set spark configuration here
    # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
    spark.executor.instances = 2
    spark.executor.cores = 1
    spark.executor.memory = "2g"
}

source {
    mongodb {
        readconfig.uri = "mongodb://core_user:xxx@10.104.20.248:27018/gizwits_core"
        readconfig.database = "gizwits_core"
        readconfig.collection = "device"
        readconfig.password = "xxx"
        readconfig.spark.mongodb.input.partitioner = "MongoPaginateBySizePartitioner"
        schema="{\"created_at\":\"date\",\"updated_at\":\"date\",\"product_key\":\"string\",\"did\":\"string\", \"passcode\":\"string\", \"mac\":\"string\"}"
        result_table_name = "core_device"
    }
}

transform {
   sql {
      sql = "SELECT created_at, updated_at, product_key,did,passcode,mac, '2022-05-10' as dt FROM core_device"
   }
   json {
      source_field = "created_at"
      new_type = "datetime"
   }
   json {
      source_field = "updated_at"
      new_type = "datetime"
   }
   json {
      source_field = "dt"
      new_type = "date"
   }
}
sink {
    clickhouse {
        host = "xxx:8123"
        database = "test"
        table = "ods_core_device"
        fields = ["created_at", "updated_at", "product_key", "did", "passcode",  "mac", "dt"]
        username = "default"
    }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh --master yarn --deploy-mode cluster --config ./config/to_clickhouse_conf/mongo_2_ck_core_device_demo.conf.template
```

### Error Exception

```log
Version 2.1.1, when using spark on yarn mode to start,[报org.apache.seatunnel.shade.com](http://xn--org-pb6f.apache.seatunnel.shade.com/) .typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'. Have you ever encountered

22/05/11 11:37:03 ERROR Seatunnel: Exception StackTrace:org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:47)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
 
22/05/11 11:37:03 ERROR Seatunnel: 
===============================================================================
```

### Flink or Spark Version

spark 2.4.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment] 2022-05-11 09:32
@BenJFan  I remember we have fixed this on dev branch?

**Comment by Hisoka-X** [comment] 2022-05-11 09:46
Please provide full log in here

**Comment by zjw-zjw** [comment] 2022-05-11 10:30
@BenJFan Here is the full log.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/emr/yarn/local/usercache/root/filecache/162/__spark_libs__8798545789667083542.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/service/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
22/05/11 11:37:03 ERROR Seatunnel: 

===============================================================================


22/05/11 11:37:03 ERROR Seatunnel: Fatal Error, 

22/05/11 11:37:03 ERROR Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

22/05/11 11:37:03 ERROR Seatunnel: Reason:No configuration setting found for key 'env' 

22/05/11 11:37:03 ERROR Seatunnel: Exception StackTrace:org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:47)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
 
22/05/11 11:37:03 ERROR Seatunnel: 
===============================================================================



22/05/11 11:37:03 ERROR ApplicationMaster: User class threw exception: org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:47)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
22/05/11 11:37:03 ERROR ApplicationMaster: Uncaught exception: 
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:468)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:779)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:778)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:803)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:47)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)

**Comment by zjw-zjw** [comment] 2022-05-13 01:39
@BenJFan Can you help me to check this? thanks ！

**Comment by Hisoka-X** [comment] 2022-05-13 01:53
> @BenJFan Can you help me to check this? thanks ！

I will check this, please wait a mement.

**Comment by gitfortian** [comment] 2022-06-21 07:15
flink run -t yarn-per-job -c org.apache.seatunnel.core.flink.SeatunnelFlink /usr/local/apache-seatunnel-incubating-2.1.2/lib/seatunnel-core-flink.jar --config ./config/flink.streaming.conf.template

flink yarn-application-mode also meet the same problem,this may be bug, because it's ok when  i run on yarn-per-job mode

**Comment by EricJoy2048** [comment] 2022-09-26 06:13
What's news?

**Comment by Hisoka-X** [comment] 2022-09-26 06:17
I can't reproduce this error. Ran fine on my env. Maybe already fix it on dev when 2.1.2 not release.

**Comment by EricJoy2048** [comment] 2022-09-26 11:59
> I can't reproduce this error. Ran fine on my env. Maybe already fix it on dev when 2.1.2 not release.

Ok, I will close this issue. If the bug reproduce in 2.1.3/dev/2.2.0 again, please reopen this issue.

**Closed as completed by EricJoy2048** 2022-09-26 11:59 UTC
Labels: bug

**Comment by kyehe** [comment] 2022-11-20 10:00
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.
> 
> ### What happened
> Version 2.1.1, when using spark on yarn mode to start,[报org.apache.seatunnel.shade.com](http://xn--org-pb6f.apache.seatunnel.shade.com/) .typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'. Have you ever encountered
> 
> ### SeaTunnel Version
> 2.1.1
> 
> ### SeaTunnel Config
> ```
> env {
>     spark.app.name = "seatunnel_mongo_to_ck_core_device_demo"
>     # You can set spark configuration here
>     # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
>     spark.executor.instances = 2
>     spark.executor.cores = 1
>     spark.executor.memory = "2g"
> }
> 
> source {
>     mongodb {
>         readconfig.uri = "mongodb://core_user:xxx@10.104.20.248:27018/gizwits_core"
>         readconfig.database = "gizwits_core"
>         readconfig.collection = "device"
>         readconfig.password = "xxx"
>         readconfig.spark.mongodb.input.partitioner = "MongoPaginateBySizePartitioner"
>         schema="{\"created_at\":\"date\",\"updated_at\":\"date\",\"product_key\":\"string\",\"did\":\"string\", \"passcode\":\"string\", \"mac\":\"string\"}"
>         result_table_name = "core_device"
>     }
> }
> 
> transform {
>    sql {
>       sql = "SELECT created_at, updated_at, product_key,did,passcode,mac, '2022-05-10' as dt FROM core_device"
>    }
>    json {
>       source_field = "created_at"
>       new_type = "datetime"
>    }
>    json {
>       source_field = "updated_at"
>       new_type = "datetime"
>    }
>    json {
>       source_field = "dt"
>       new_type = "date"
>    }
> }
> sink {
>     clickhouse {
>         host = "xxx:8123"
>         database = "test"
>         table = "ods_core_device"
>         fields = ["created_at", "updated_at", "product_key", "did", "passcode",  "mac", "dt"]
>         username = "default"
>     }
> }
> ```
> 
> ### Running Command
> ```shell
> ./bin/start-seatunnel-spark.sh --master yarn --deploy-mode cluster --config ./config/to_clickhouse_conf/mongo_2_ck_core_device_demo.conf.template
> ```
> 
> ### Error Exception
> ```
> Version 2.1.1, when using spark on yarn mode to start,[报org.apache.seatunnel.shade.com](http://xn--org-pb6f.apache.seatunnel.shade.com/) .typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'. Have you ever encountered
> 
> 22/05/11 11:37:03 ERROR Seatunnel: Exception StackTrace:org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'env'
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
> 	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
> 	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:47)
> 	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
> 	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
> 	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
> 	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
> 	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:27)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
>  
> 22/05/11 11:37:03 ERROR Seatunnel: 
> ===============================================================================
> ```
> 
> ### Flink or Spark Version
> spark 2.4.3
> 
> ### Java or Scala Version
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

hi is this problom solved in the newest dev branch? I met this again..

**Comment by whateverDebug** [comment] 2024-05-22 03:29
I encountered the same issue where the operations personnel mistakenly wrote a configuration item "env" in the script for the running task as "nv", causing the seatunnel to throw the same error.
