### ISSUE TITLE
[Bug] [seatunnel-connector-flink-druid] The data source is Druid, hint Plugin class not found by name :[DruidSource]

### ISSUE THREAD

**Issue by TYJ0716** [apache/seatunnel#1899] opened 2022-05-17 12:02 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In version 2.1.1, when I use druid as my data source, THE Plugin for DruidSource cannot be found

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
    DruidSource{
      jdbc_url = "jdbc:avatica:remote:url=http://localhost:8082/druid/v2/sql/avatica/"
      datasource = "WorkflowMetrics"
      start_date = "2021-00-00 00:00:00"
      end_date = "2021-12-21 23:59:59"
      columns = ["counter","countryId"]
    }
}
sink {
  ConsoleSink {}

  # If you would like to get more information about how to configure seatunnel and see full list of output plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/sink-plugins/Console
}
```

### Running Command

```shell
./bin/start-seatunnel-flink.sh --config ./config/flink_druid_to_console
```

### Error Exception

```log
The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: java.lang.ClassNotFoundException: Plugin class not found by name :[DruidSource]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Plugin class not found by name :[DruidSource]
	at org.apache.seatunnel.config.PluginFactory.lambda$createPlugins$0(PluginFactory.java:96)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.apache.seatunnel.config.PluginFactory.createPlugins(PluginFactory.java:90)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:52)
	at org.apache.seatunnel.command.flink.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:47)
	at org.apache.seatunnel.command.flink.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:39)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 8 more
Caused by: java.lang.ClassNotFoundException: Plugin class not found by name :[DruidSource]
	at org.apache.seatunnel.config.PluginFactory.createPluginInstanceIgnoreCase(PluginFactory.java:132)
	at org.apache.seatunnel.config.PluginFactory.lambda$createPlugins$0(PluginFactory.java:92)
	... 20 more
```

### Flink or Spark Version

Flink 1.13.5

### Java or Scala Version

1.8.0_181

### Screenshots

![image](https://user-images.githubusercontent.com/58028162/168805839-7d4110d1-af02-41f4-a72b-ca2df30746da.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment] 2022-05-18 01:56
@TYJ0716 This is caused by the druid connector is not in distribution, you can add below dependency at seatunnel-core-flink/pom.xml, and use `mvn clean package` to make a new distribution.
```xml
<dependency>
        <groupId>org.apache.seatunnel</groupId>
        <artifactId>seatunnel-connector-flink-druid</artifactId>
        <version>${project.version}</version>
</dependency>
```

**Comment by ruanwenjun** [comment] 2022-05-18 01:57
And this has already fixed at dev branch, I will close this issue.

**Closed as completed by ruanwenjun** 2022-05-18 01:57 UTC
Labels: bug
