### ISSUE TITLE
ERROR Seatunnel: Reason:SQL validation failed. From line 1, column 28 to line 1, column 40: Object 'user_20211216' not found

### ISSUE THREAD

**Issue by lihjChina** [apache/seatunnel#1096] opened 2022-01-19 03:49 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use samples to test the connector-flink-jdbc ，but fond the error 
ERROR Seatunnel: Reason:SQL validation failed. From line 1, column 28 to line 1, column 40: Object 'user_20211216' not found

I'm always looking forward to your reply at your earliest convenience. Thanks

### SeaTunnel Version

the dev

### SeaTunnel Config

```conf
my config is 
env {
  execution.parallelism = 1
}
source {
    JdbcSource {
        driver = com.mysql.cj.jdbc.Driver
        url = "jdbc:mysql://192.168.80.163:3306/li_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false"
        username = root
        password = xxx
        query = "select * from user_20211216"
    }
}
transform {
    sql {
      sql = "select username,role from  user_20211216",
      table_name ="user_20211216"
    }
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
String configFile = getTestConfigFile("jdbc_to_console.conf");
 CommandLineArgs flinkArgs = new CommandLineArgs(configFile, false);
 Seatunnel.run(flinkArgs, FLINK, args);
```

### Error Exception

```log
22/01/19 11:42:02 ERROR Seatunnel: Exception StackTrace:org.apache.flink.table.api.ValidationException: SQL validation failed. From line 1, column 28 to line 1, column 40: Object 'user_20211216' not found
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:128)
	at org.apache.flink.table.api.internal.TableEnvImpl.sqlQuery(TableEnvImpl.scala:431)
	at org.apache.seatunnel.flink.transform.Sql.processBatch(Sql.java:52)
	at org.apache.seatunnel.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:66)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:102)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:60)
	at org.apache.seatunnel.example.flink.litest.JDBCFlinkExample.main(JDBCFlinkExample.java:32)
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 1, column 28 to line 1, column 40: Object 'user_20211216' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:824)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:809)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4807)
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:172)
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:177)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:997)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:957)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3111)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3093)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3365)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:997)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:957)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:932)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:639)
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:124)
	... 6 more
```

### Java or Scala Version

jdk1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lihjchain** [comment] 2022-01-19 04:46
if I dont use the transform fond the error
org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:627)
	at org.apache.flink.client.LocalExecutor.executePlan(LocalExecutor.java:222)
	at org.apache.flink.api.java.LocalEnvironment.execute(LocalEnvironment.java:91)
	at org.apache.seatunnel.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:80)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:102)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:60)
	at org.apache.seatunnel.example.flink.litest.JDBCFlinkExample.main(JDBCFlinkExample.java:32)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
	at org.apache.flink.api.common.typeutils.base.ByteSerializer.serialize(ByteSerializer.java:32)
	at org.apache.flink.api.java.typeutils.runtime.RowSerializer.serialize(RowSerializer.java:161)
	at org.apache.flink.api.java.typeutils.runtime.RowSerializer.serialize(RowSerializer.java:44)
	at org.apache.flink.runtime.plugable.SerializationDelegate.write(SerializationDelegate.java:54)
	at org.apache.flink.runtime.io.network.api.serialization.SpanningRecordSerializer.serializeRecord(SpanningRecordSerializer.java:78)
	at org.apache.flink.runtime.io.network.api.writer.RecordWriter.emit(RecordWriter.java:152)
	at org.apache.flink.runtime.io.network.api.writer.RecordWriter.emit(RecordWriter.java:120)
	at org.apache.flink.runtime.operators.shipping.OutputCollector.collect(OutputCollector.java:65)
	at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
	at org.apache.flink.runtime.operators.DataSourceTask.invoke(DataSourceTask.java:196)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
Disconnected from the target VM, address: '127.0.0.1:52283', transport: 'socket'

**Comment by liunaijie** [comment] 2024-11-15 01:22
close it as not active

**Closed as completed** 2024-11-15 01:21 UTC
Labels: bug
