### ISSUE TITLE
运行2.3.3版本，官方文档快速开始 报错找不到FakeSource，其他插件也是找不到

### ISSUE THREAD

**Issue by 1498658503** [apache/seatunnel#5464] opened 2023-09-12 02:10 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Caused by: java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSource'} not found.

我已经按照官网步骤，下载apache-seatunnel-2.3.3-bin.tar.gz  并且执行了sh bin/install-plugin.sh 2.3.3     
插件已经在..../apache-seatunnel-2.3.3/connectors/seatunnel目录下了，但是依然是找不到

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

transform {
  FieldMapper {
    source_table_name = "fake"
    result_table_name = "fake1"
    field_mapper = {
      age = age
      name = new_name
    }
  }
}

sink {
  Console {
    source_table_name = "fake1"
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink-13-connector-v2.sh --config ./config/v2.streaming.conf.template
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSource'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:223)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:61)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:77)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:298)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:159)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment] 2023-09-12 08:15
Most of this problem is caused by not installing plugins. You can refer to https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/deployment to fixed it.

**Comment by EricJoy2048** [comment] 2023-09-12 08:16
Also, please change the title to English.
Thanks.

**Comment by 1498658503** [comment] 2023-09-12 08:22
Running version 2.3.3, the official documentation starts quickly FakeSource cannot be found with an error, and other plugins cannot be found .
But I've successfully executed the plugin download script, and the jar package can be found in the ..../apache-seatunnel-2.3.3/connectors/seatunnel directory

**Comment by 1498658503** [comment] 2023-09-12 08:23
> Also, please change the title to English. Thanks.

Running version 2.3.3, the official documentation starts quickly FakeSource cannot be found with an error, and other plugins cannot be found .
But I've successfully executed the plugin download script, and the jar package can be found in the ..../apache-seatunnel-2.3.3/connectors/seatunnel directory

**Comment by EricJoy2048** [comment] 2023-09-12 08:45
> > Also, please change the title to English. Thanks.
> 
> Running version 2.3.3, the official documentation starts quickly FakeSource cannot be found with an error, and other plugins cannot be found . But I've successfully executed the plugin download script, and the jar package can be found in the ..../apache-seatunnel-2.3.3/connectors/seatunnel directory

It's strange, I'm not sure what engine you're using. If it's a Flink engine, there shouldn't be any seatunnel engine related logs in the logs.

**Comment by EricJoy2048** [comment] 2023-09-12 08:52
If you use seatunnel zeta engine, you can submit job by `./bin/seatunnel.sh -c ./config/v2.streaming.conf.template -e local`

**Comment by CheneyYin** [comment] 2023-09-13 08:35
> > Also, please change the title to English. Thanks.
> 
> Running version 2.3.3, the official documentation starts quickly FakeSource cannot be found with an error, and other plugins cannot be found . But I've successfully executed the plugin download script, and the jar package can be found in the ..../apache-seatunnel-2.3.3/connectors/seatunnel directory

Did you add `connnector-fake` to `config/plugin_config`?

**Comment by lfift** [comment] 2023-09-19 04:55
按照官网这个教程来的报错如下：
教程：https://seatunnel.incubator.apache.org/docs/2.3.3/start-v2/locally/deployment
https://seatunnel.incubator.apache.org/docs/2.3.3/start-v2/locally/quick-start-seatunnel-engine
![image](https://github.com/apache/seatunnel/assets/31279478/9f579d17-4c47-4c0d-acb9-b7db8a3008b1)
![image](https://github.com/apache/seatunnel/assets/31279478/f450bbda-b87d-4e8f-a7f5-dbb3212c1517)
![image](https://github.com/apache/seatunnel/assets/31279478/771a2e3c-afbe-4384-bd45-50a0acc53655)

执行./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local报错如下
org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-302724] [5.1] submit job 756376511967133697 error java.lang.NoClassDefFoundError: com/sun/jersey/client/impl/CopyOnWriteHashMap

**Comment by qinlz-1** [comment] 2023-09-19 06:30
@EricJoy2048 
submit to flink yarn 
command：./bin/start-seatunnel-flink-15-connector-v2.sh --config ./config/v2.streaming.conf.template -e run-application --master yarn-application 
error:
2023-09-12 14:48:33,076 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery [] - Load SeaTunnelSource Plugin from /data1/yarn/nm/usercache/hdfs/appcache/application_1694423394568_0024/connectors/seatunnel
2023-09-12 14:48:33,084 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - 

===============================================================================


2023-09-12 14:48:33,084 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Fatal Error, 

2023-09-12 14:48:33,084 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-09-12 14:48:33,084 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Reason:Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSource'} not found. 

seatunnel can not upload connectors/seatunnel  plugins jar to yarn

**Comment by hailin0** [comment] 2023-09-19 08:39
Close this issue because https://github.com/apache/seatunnel/issues/5464 already exists

**Closed as completed by hailin0** 2023-09-19 08:39 UTC
Labels: Usage Error

**Comment by qinlz-1** [comment] 2023-09-20 02:48
@hailin0 
Same error, but for different reasons.
#5464 look like submit job   to local, I think he may not have activated the  flink standalone server。
But in my case，seatunnel cannot submit connectors/seatunnel directories to yarn

**Comment by AsLightJava** [comment] 2023-10-11 06:36
I met the same problem,how to solve it?

**Comment by AsLightJava** [comment] 2023-10-11 08:04
I find the solve way, it may be you change apache-seatunnel-2.3.3  to another dir name, you need to change dir name to apache-seatunnel-2.3.3 , i think it may cause by path

**Comment by qinlz-1** [comment] 2023-10-25 03:24
@AsLightJava 
I did not change the apache-seatunnel-2.3.3 directory name

**Comment by AsLightJava** [comment] 2023-10-25 03:30
please give me your config and path picture



---Original---
From: ***@***.***&gt;
Sent at: 2023年10月25日(Wed) Noon11:24
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/seatunnel] 运行2.3.3版本，官方文档快速开始 报错找不到FakeSource，其他插件也是找不到 (Issue #5464)




 
@AsLightJava
 I did not change the apache-seatunnel-2.3.3 directory name

**Comment by supercena** [comment] 2023-10-31 05:53
可能是环境变量 路径不对

**Comment by qinlz-1** [comment] 2023-10-31 08:30
@AsLightJava 
**plugin_config :**
--connectors-v2--
connector-console
connector-fake
--end--

**path :** 
![image](https://github.com/apache/seatunnel/assets/80371132/8d8bcab1-592d-4f65-80e6-15eedc415ae8)
**command :** 
bin/start-seatunnel-flink-15-connector-v2.sh --config ./config/v2.batch.config.template --deploy-mode run-application --target yarn-application

**Comment by qinlz-1** [comment] 2023-10-31 08:31
@supercena 
没有配置什么环境变量

**Comment by liutianyuan** [comment] 2023-12-08 13:56
请问这个问题解决了吗，我也遇到了同样的问题

**Comment by qinlz-1** [comment] 2024-01-24 08:12
@liutianyuan 
没解决，不确定，官方是否测试过这种提交方式。理论上应该测了，是不是有什么需要特别的配置官网上也没有

**Comment by lishixionghg** [comment] 2024-02-21 02:38
the plugins should be apache-seatunnel/connectors/${engine-type}/

**Comment by sjzAValon** [comment] 2024-05-08 01:39
connectors/seatunnel下所有的jar包都拷贝到lib目录下试试

**Comment by qinlz-1** [comment] 2024-05-17 02:58
@lishixionghg 
This method has been tried, but the same error has been reported
@AsLightJava 
试过了，还是报错
![image](https://github.com/apache/seatunnel/assets/80371132/2c745c22-9b90-472a-9013-8d1416b5f83f)
![image](https://github.com/apache/seatunnel/assets/80371132/a4d7f776-eb3b-4a68-9c2b-570dde2466b3)

**Comment by papadave66** [comment] 2025-07-09 02:50
你需要检查connectors文件夹内的 plugin-mapping.properties  是不是把对应的插件注释掉了，我是在这儿看到的相关文章
https://blog.csdn.net/qq_24045275/article/details/140795599
